"""
Django settings for appProjet project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-#-^-_h)qal8xx_^jud5*^q5n^q1-x1g8cfs)-v-n8*)#=1qa2=')
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # other Django apps linked to tailwindcss
    'tailwind',
    'theme',
    # application
    'cockpit'
]

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload',]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware',]

ROOT_URLCONF = 'appProjet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appProjet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Conf par défaut avec utilisation de sqlite
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

TAILWIND_APP_NAME = 'theme'

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Tant que l'application n'est pas enregistrée dans Azure AD, ce flag
# empêche tout appel réel à Microsoft Graph (voir views.py). À passer
# à True (ou dans .env : SHAREPOINT_ENABLED=True) une fois l'autorisation
# obtenue.
SHAREPOINT_ENABLED = config('SHAREPOINT_ENABLED', default=False, cast=bool)
 
SP_TENANT_ID = config('SP_TENANT_ID', default='')
SP_CLIENT_ID = config('SP_CLIENT_ID', default='')
SP_CLIENT_SECRET = config('SP_CLIENT_SECRET', default='')


# localisation du dossier de stockage dans SharePoint
# emplacement définitif à définir avec l'IT
# un dossier lié à chaque projet / contact sera créé à la volée
SP_SITE_HOSTENAME = "vedecominstitut.sharepoint.com"
SP_SITE_PATH = "sites/vedecom-ds" # temporaire, un emplacement pour les différents documents devras être déterminé

# dossiers spécifiques aux types de formulaires:
# permet de ne pas mélanger les documents liés aux projet avec ceux liés aux contacts
# des sous-dossiers sont créés dynamiquements pour lier chaque document à son projet ou contact
SP_FOLDER = {
    "contact": "CRM/Contacts",
    "projets": "Projets",
    "theses": "Theses",
}