# Generated by Django 6.0.6 on 2026-07-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(db_column='action_id', primary_key=True, serialize=False)),
                ('type_action', models.CharField(blank=True, db_column='type_action', max_length=50, null=True)),
                ('objet_action', models.CharField(blank=True, db_column='objet_action', max_length=100, null=True)),
                ('commentaire_action', models.CharField(blank=True, db_column='commentaire_action', max_length=500, null=True)),
                ('date_action', models.DateField(blank=True, db_column='date_action', null=True)),
                ('statut_action', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
                ('update_by', models.CharField(db_column='update_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"crm"."action"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('auteur_id', models.AutoField(db_column='auteur_id', primary_key=True, serialize=False)),
                ('nom_auteur', models.CharField(blank=True, db_column='nom_auteur', max_length=100, null=True)),
                ('prenom_auteur', models.CharField(blank=True, db_column='prenom_auteur', max_length=100, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."auteur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('comment_id', models.AutoField(db_column='comment_id', primary_key=True, serialize=False)),
                ('commentaire', models.CharField(blank=True, db_column='commentaire', max_length=1500, null=True)),
                ('finance_comment', models.BooleanField(db_column='finance_comment', default=False)),
                ('create_at', models.DateTimeField(blank=True, db_column='create_at', null=True)),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."commentaire"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaireThese',
            fields=[
                ('comm_these_id', models.AutoField(db_column='comm_these_id', primary_key=True, serialize=False)),
                ('commentaire', models.CharField(blank=True, db_column='commentaire', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."commentaire_these"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentCrm',
            fields=[
                ('comment_crm_id', models.AutoField(db_column='comment_crm_id', primary_key=True, serialize=False)),
                ('commentaire_crm', models.CharField(blank=True, db_column='commentaire_crm', max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"crm"."comment_crm"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentEvent',
            fields=[
                ('comment_event_id', models.AutoField(db_column='comment_event_id', primary_key=True, serialize=False)),
                ('commentaire_event', models.CharField(blank=True, db_column='commentaire_event', max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"evenementiel"."comment_event"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentLivrable',
            fields=[
                ('comment_livrable_id', models.AutoField(db_column='comment_livrable_id', primary_key=True, serialize=False)),
                ('commentaire', models.CharField(blank=True, db_column='commentaire', max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."comment_livrable"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(db_column='contact_id', primary_key=True, serialize=False)),
                ('prenom_contact', models.CharField(blank=True, db_column='prenom_contact', max_length=50, null=True)),
                ('nom_contact', models.CharField(blank=True, db_column='nom_contact', max_length=50, null=True)),
                ('email_contact', models.EmailField(blank=True, db_column='email_contact', max_length=100, null=True)),
                ('telephone_contact', models.CharField(blank=True, db_column='telephone_contact', max_length=20, null=True)),
                ('poste_contact', models.CharField(blank=True, db_column='poste_contact', max_length=50, null=True)),
                ('statut_kanban', models.CharField(blank=True, db_column='statut_kanban', max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"crm"."contact"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeEvent',
            fields=[
                ('demande_id', models.AutoField(db_column='demande_id', primary_key=True, serialize=False)),
                ('horaire', models.TimeField(blank=True, db_column='horaire', null=True)),
                ('type_event', models.CharField(blank=True, db_column='type_event', max_length=255, null=True)),
                ('budget_prevu', models.BooleanField(blank=True, db_column='budget_prevu', null=True)),
                ('budget_prevu_montant', models.DecimalField(blank=True, db_column='budget_prevu_montant', decimal_places=2, max_digits=5, null=True)),
                ('nb_participant', models.SmallIntegerField(db_column='nb_participant', default=0)),
                ('espace', models.CharField(blank=True, db_column='espace', max_length=50, null=True)),
                ('parking', models.BooleanField(db_column='parking', default=False)),
                ('sono', models.BooleanField(db_column='sono', default=False)),
                ('informatique', models.BooleanField(db_column='informatique', default=False)),
                ('demo', models.BooleanField(db_column='demo', default=False)),
                ('demo_description', models.CharField(blank=True, db_column='demo_description', max_length=150, null=True)),
                ('restauration', models.BooleanField(db_column='restauration', default=False)),
                ('logistique_intervenant', models.BooleanField(db_column='logistique_intervenant', default=False)),
                ('infos_complementaire', models.CharField(blank=True, db_column='infos_complementaire', max_length=500, null=True)),
                ('statut_event', models.CharField(blank=True, db_column='statut_event', max_length=20, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"evenementiel"."demande_event"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(db_column='doc_id', primary_key=True, serialize=False)),
                ('type_doc', models.CharField(blank=True, db_column='type_doc', max_length=100, null=True)),
                ('nom_doc', models.CharField(blank=True, db_column='nom_doc', max_length=150, null=True)),
                ('doc_ok', models.BooleanField(db_column='doc_ok', default=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."document"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('domaine_id', models.AutoField(db_column='domaine_id', primary_key=True, serialize=False)),
                ('nom_domaine', models.CharField(blank=True, db_column='nom_domaine', max_length=150, null=True)),
                ('num_domaine', models.SmallIntegerField(blank=True, db_column='num_domaine', null=True)),
                ('domaine_archive', models.BooleanField(db_column='domaine_archive', default=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."domaine"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomaineProjet',
            fields=[
                ('pk', models.CompositePrimaryKey('projet_id', 'domaine_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('principale', models.BooleanField(db_column='principale', default=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."domaine_projet"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('echeance_id', models.AutoField(db_column='echeance_id', primary_key=True, serialize=False)),
                ('deadline', models.DateField(blank=True, db_column='deadline', null=True)),
                ('type_echeance', models.CharField(blank=True, db_column='type_echeance', max_length=100, null=True)),
                ('commentaire', models.CharField(blank=True, db_column='commentaire', max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."echeance"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncadrantExt',
            fields=[
                ('pk', models.CompositePrimaryKey('contact_id', 'these_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."encadrant_ext"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('entite_id', models.AutoField(db_column='entite_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='nom_entite', max_length=150, null=True)),
                ('type_entite', models.CharField(blank=True, db_column='type_entite', max_length=50, null=True)),
                ('secteur_entite', models.CharField(blank=True, db_column='secteur_entite', max_length=50, null=True)),
                ('adresse_entite', models.CharField(blank=True, db_column='adresse_entite', max_length=200, null=True)),
                ('url_entite', models.CharField(blank=True, db_column='url_entite', max_length=100, null=True)),
                ('telephone_entite', models.CharField(blank=True, db_column='telephone_entite', max_length=20, null=True)),
                ('statut_entite', models.CharField(blank=True, db_column='statut_entite', max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"crm"."entite"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('equipe_id', models.AutoField(db_column='equipe_id', primary_key=True, serialize=False)),
                ('nom_equipier', models.CharField(blank=True, db_column='nom_equipier', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."equipe"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvalBenefice',
            fields=[
                ('eval_id', models.AutoField(db_column='eval_id', primary_key=True, serialize=False)),
                ('type_eval', models.CharField(choices=[('benefice', 'Bénéfice'), ('contre_benefice', 'Contre-bénéfice')], db_column='type_eval', max_length=20)),
                ('contenu', models.TextField(db_column='contenu')),
            ],
            options={
                'db_table': '"projet_mgmt"."eval_benefice"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(db_column='event_id', primary_key=True, serialize=False)),
                ('nom_event', models.CharField(blank=True, db_column='nom_event', max_length=150, null=True)),
                ('date_event', models.DateField(blank=True, db_column='date_event', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"evenementiel"."event"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceAnnee',
            fields=[
                ('finance_proj_id', models.AutoField(db_column='finance_proj_id', primary_key=True, serialize=False)),
                ('num_annee', models.SmallIntegerField(blank=True, db_column='num_annee', default=0, null=True)),
                ('person_month', models.DecimalField(blank=True, db_column='person_month', decimal_places=2, max_digits=10, null=True)),
                ('frais_env_structure', models.DecimalField(blank=True, db_column='frais_env_structure', decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, db_column='total', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."finance_annee"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Financeur',
            fields=[
                ('financeur_id', models.AutoField(db_column='financeur_id', primary_key=True, serialize=False)),
                ('type_finance', models.CharField(blank=True, db_column='type_finance', max_length=50, null=True)),
                ('montant_finance', models.DecimalField(blank=True, db_column='montant_finance', decimal_places=2, max_digits=10, null=True)),
                ('type_contribution', models.CharField(blank=True, db_column='type_contribution', max_length=20, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."financeur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeureVacation',
            fields=[
                ('heure_id', models.AutoField(db_column='heure_id', primary_key=True, serialize=False)),
                ('date_cours', models.DateField(blank=True, db_column='date_cours', null=True)),
                ('heure_debut', models.TimeField(blank=True, db_column='heure_debut', null=True)),
                ('heure_fin', models.TimeField(blank=True, db_column='heure_fin', null=True)),
                ('type_cours', models.CharField(blank=True, choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques')], db_column='type_cours', max_length=2, null=True)),
                ('nb_heure', models.DecimalField(blank=True, db_column='nb_heure', decimal_places=2, max_digits=4, null=True)),
                ('validation_dd', models.CharField(blank=True, db_column='validation_dd', max_length=150, null=True)),
                ('validation_ds', models.CharField(blank=True, db_column='validation_ds', max_length=150, null=True)),
                ('validation_daf', models.CharField(blank=True, db_column='validation_daf', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."heure_vacation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteretMembre',
            fields=[
                ('interet_id', models.AutoField(db_column='interet_id', primary_key=True, serialize=False)),
                ('commentaire_interet', models.CharField(blank=True, db_column='commentaire_interet', max_length=255, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."interet_membre"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LieuProjet',
            fields=[
                ('lieu_id', models.AutoField(db_column='lieu_id', primary_key=True, serialize=False)),
                ('nom_lieu', models.CharField(blank=True, db_column='nom_lieu', max_length=100, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."lieu_projet"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListeInvite',
            fields=[
                ('list_invite_id', models.AutoField(db_column='list_invite_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"evenementiel"."liste_invite"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('livrable_id', models.AutoField(db_column='livrable_id', primary_key=True, serialize=False)),
                ('identifiant', models.CharField(blank=True, db_column='identifiant', max_length=150, null=True)),
                ('intitule', models.CharField(blank=True, db_column='intitule', max_length=100, null=True)),
                ('depot', models.BooleanField(db_column='depot', default=False)),
                ('responsable', models.CharField(blank=True, db_column='responsable', max_length=150, null=True)),
                ('nature_livrable', models.CharField(blank=True, db_column='nature_livrable', max_length=50, null=True)),
                ('previ_initial', models.DateField(blank=True, db_column='previ_initial', null=True)),
                ('reprevision', models.DateField(blank=True, db_column='reprevision', null=True)),
                ('nb_reprevision', models.SmallIntegerField(db_column='nb_reprevision', default=0)),
                ('date_livraison', models.DateField(blank=True, db_column='date_livraison', null=True)),
                ('percent_realisation', models.SmallIntegerField(db_column='percent_realisation', default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."livrable"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('lot_id', models.AutoField(db_column='lot_id', primary_key=True, serialize=False)),
                ('num_lot', models.SmallIntegerField(db_column='num_lot', default=0)),
                ('description_lot', models.CharField(db_column='description_lot', max_length=1500)),
                ('recherche_fonda', models.SmallIntegerField(db_column='recherche_fonda', default=0)),
                ('recherche_indus', models.SmallIntegerField(db_column='recherche_indus', default=0)),
                ('dev_experimental', models.SmallIntegerField(db_column='dev_experimental', default=0)),
                ('etude_faisable', models.SmallIntegerField(db_column='etude_faisable', default=0)),
            ],
            options={
                'db_table': '"projet_mgmt"."lot"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('partenaire_id', models.AutoField(db_column='partenaire_id', primary_key=True, serialize=False)),
                ('commentaire', models.CharField(blank=True, db_column='commentaire', max_length=500, null=True)),
                ('date_association', models.DateField(blank=True, db_column='date_association', null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."partenaire"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartenaireLot',
            fields=[
                ('pk', models.CompositePrimaryKey('lot_id', 'partenaire_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."partenaire_lot"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('participation_id', models.AutoField(db_column='participation_id', primary_key=True, serialize=False)),
                ('assistance_com', models.BooleanField(db_column='assistance_com', default=False)),
                ('assistance_action', models.CharField(blank=True, db_column='assistance_action', max_length=150, null=True)),
                ('ville', models.CharField(blank=True, db_column='ville', max_length=100, null=True)),
                ('pays', models.CharField(blank=True, db_column='pays', max_length=50, null=True)),
                ('referent', models.CharField(blank=True, db_column='referent', max_length=150, null=True)),
                ('domaine', models.SmallIntegerField(blank=True, db_column='domaine', null=True)),
                ('role', models.CharField(blank=True, db_column='role', max_length=100, null=True)),
                ('activite', models.CharField(blank=True, db_column='activite', max_length=100, null=True)),
                ('objectif', models.CharField(blank=True, db_column='objectif', max_length=100, null=True)),
                ('organisateur', models.CharField(blank=True, db_column='organisateur', max_length=100, null=True)),
                ('orga_vedecom', models.BooleanField(db_column='orga_vedecom', default=False)),
                ('commentaire_participation', models.CharField(blank=True, db_column='commentaire_participation', max_length=500, null=True)),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"evenementiel"."participation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgStrategique',
            fields=[
                ('strat_id', models.AutoField(db_column='strat_id', primary_key=True, serialize=False)),
                ('nom_strat', models.CharField(blank=True, db_column='nom_strat', max_length=100, null=True)),
                ('strat_archive', models.BooleanField(db_column='strat_archive', default=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."prog_strategique"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('projet_id', models.AutoField(db_column='projet_id', primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(blank=True, db_column='nom_projet', max_length=255, null=True)),
                ('acronyme_projet', models.CharField(blank=True, db_column='acronyme_projet', max_length=50, null=True)),
                ('confidentiel', models.BooleanField(db_column='confidentiel', default=False)),
                ('statut_actuel', models.CharField(choices=[('vivier', 'Vivier'), ('cadrage', 'Cadrage'), ('montage', 'Montage'), ('soumission', 'Soumission'), ('en_cours_non_valide', 'En cours non Validé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('clos', 'Clos')], db_column='statut_actuel', default='vivier', max_length=50)),
                ('date_debut_prevu', models.DateField(blank=True, db_column='date_debut_prevu', null=True)),
                ('date_fin_prevu', models.DateField(blank=True, db_column='date_fin_prevu', null=True)),
                ('date_debut_reel', models.DateField(blank=True, db_column='date_debut_reel', null=True)),
                ('date_fin_reel', models.DateField(blank=True, db_column='date_fin_reel', null=True)),
                ('type_projet', models.CharField(blank=True, db_column='type_projet', max_length=50, null=True)),
                ('nom_appel_contrat', models.CharField(blank=True, db_column='nom_appel_contrat', max_length=500, null=True)),
                ('contrib_vedecom', models.CharField(blank=True, db_column='contrib_vedecom', max_length=500, null=True)),
                ('reussite_estime', models.PositiveSmallIntegerField(blank=True, db_column='reussite_estime', default=0)),
                ('event_kickoff', models.CharField(blank=True, db_column='event_kickoff', max_length=10, null=True)),
                ('event_middle', models.CharField(blank=True, db_column='event_middle', max_length=10, null=True)),
                ('event_fin', models.CharField(blank=True, db_column='event_fin', max_length=10, null=True)),
                ('call_eu', models.CharField(blank=True, db_column='call_eu', max_length=500, null=True)),
                ('ngrant_eu', models.PositiveSmallIntegerField(blank=True, db_column='ngrant_eu', null=True)),
                ('core_group_eu', models.BooleanField(blank=True, db_column='core_group_eu', null=True)),
                ('sr_pilot_eu', models.BooleanField(blank=True, db_column='sr_pilot_eu', null=True)),
                ('lump_sum_eu', models.BooleanField(blank=True, db_column='lump_sum_eu', null=True)),
                ('pm_valide', models.DecimalField(blank=True, db_column='pm_valide', decimal_places=2, max_digits=5, null=True)),
                ('pm_rate_projet', models.DecimalField(blank=True, db_column='pm_rate_projet', decimal_places=2, max_digits=5, null=True)),
                ('budget_total', models.DecimalField(blank=True, db_column='budget_total', decimal_places=2, max_digits=10, null=True)),
                ('budget_vedecom', models.DecimalField(blank=True, db_column='budget_vedecom', decimal_places=2, max_digits=10, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
                ('update_by', models.CharField(blank=True, db_column='update_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."projet"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(db_column='publication_id', primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, db_column='titre', max_length=500, null=True)),
                ('url_doi', models.CharField(blank=True, db_column='url_doi', max_length=500, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."publication"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubliThese',
            fields=[
                ('pk', models.CompositePrimaryKey('publication_id', 'these_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('comm_publi_these', models.CharField(blank=True, db_column='comm_publi_these', max_length=500, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."publi_these"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('responsable_id', models.AutoField(db_column='responsable_id', primary_key=True, serialize=False)),
                ('nom_responsable', models.CharField(blank=True, db_column='nom_responsable', max_length=150, null=True)),
                ('cadrage_projet', models.BooleanField(db_column='cadrage_projet', default=False)),
                ('montage_projet', models.BooleanField(db_column='montage_projet', default=False)),
                ('chef_projet', models.BooleanField(db_column='chef_projet', default=False)),
            ],
            options={
                'db_table': '"projet_mgmt"."responsable"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restauration',
            fields=[
                ('restauration_id', models.AutoField(db_column='restauration_id', primary_key=True, serialize=False)),
                ('type_repas', models.CharField(blank=True, db_column='type_repas', max_length=100, null=True)),
            ],
            options={
                'db_table': '"evenementiel"."restauration"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sstache',
            fields=[
                ('sstache_id', models.AutoField(db_column='sstache_id', primary_key=True, serialize=False)),
                ('num_sstache', models.SmallIntegerField(blank=True, db_column='num_sstache', null=True)),
                ('delai', models.SmallIntegerField(blank=True, db_column='delai', null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."sstache"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('tache_id', models.AutoField(db_column='tache_id', primary_key=True, serialize=False)),
                ('num_tache', models.SmallIntegerField(blank=True, db_column='num_tache', null=True)),
                ('description_tache', models.CharField(blank=True, db_column='description_tache', max_length=255, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."tache"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('these_id', models.AutoField(db_column='these_id', primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, db_column='date_debut', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='date_fin', null=True)),
                ('nb_annee', models.SmallIntegerField(blank=True, db_column='nb_annee', null=True)),
                ('fin_contrat', models.BooleanField(db_column='fin_contrat', default=False)),
                ('soutenue', models.BooleanField(db_column='soutenue', default=False)),
                ('date_soutenance', models.DateField(blank=True, db_column='date_soutenance', null=True)),
                ('etat_memoire', models.SmallIntegerField(blank=True, db_column='etat_memoire', null=True)),
                ('ecole_doc', models.CharField(blank=True, db_column='ecole_doc', max_length=100, null=True)),
                ('cnu', models.SmallIntegerField(blank=True, db_column='cnu', null=True)),
                ('sujet', models.CharField(blank=True, db_column='sujet', max_length=300, null=True)),
                ('thematique', models.CharField(blank=True, db_column='thematique', max_length=1000, null=True)),
                ('encadrant_int', models.CharField(blank=True, db_column='encadrant_int', max_length=150, null=True)),
                ('valorisation', models.CharField(blank=True, db_column='valorisation', max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True)),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
                ('update_by', models.CharField(blank=True, db_column='update_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."these"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vacation_id', models.AutoField(db_column='vacation_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='nom', max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, db_column='prenom', max_length=100, null=True)),
                ('intitule', models.CharField(blank=True, db_column='intitule', max_length=100, null=True)),
                ('diplome', models.CharField(blank=True, db_column='diplome', max_length=150, null=True)),
                ('annee', models.SmallIntegerField(blank=True, db_column='annee', null=True)),
                ('lmd_universite', models.CharField(blank=True, db_column='lmd_universite', max_length=2, null=True)),
                ('infos_complementaire', models.CharField(blank=True, db_column='infos_complementaire', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."vacation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('validation_id', models.AutoField(db_column='validation_id', primary_key=True, serialize=False)),
                ('statut_atteint', models.CharField(blank=True, db_column='statut_atteint', max_length=20, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('create_by', models.CharField(blank=True, db_column='create_by', max_length=150, null=True)),
            ],
            options={
                'db_table': '"projet_mgmt"."validation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs_projet', models.TextField(blank=True, null=True)),
                ('axes_feuille_route', models.TextField(blank=True, null=True)),
                ('principaux_resultats', models.TextField(blank=True, null=True)),
                ('besoins_materiels_logiciels', models.TextField(blank=True, null=True)),
                ('theses_prevues', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('projet', models.OneToOneField(db_column='projet_id', on_delete=django.db.models.deletion.CASCADE, related_name='description_scientifique', to='cockpit.projet')),
            ],
            options={
                'db_table': '"projet_mgmt"."description_scientifique"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentSharepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nom_fichier', models.CharField(max_length=255)),
                ('sharepoint_folder_path', models.CharField(max_length=500)),
                ('sharepoint_folder_url', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'managed': True,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='cockpit_doc_content_790a35_idx')],
            },
        ),
    ]
