# Generated by Django 6.0.6 on 2026-07-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE public.cockpit_documentsharepoint '
                        'RENAME TO document_sharepoint;\n'
                        'ALTER TABLE public.document_sharepoint '
                        'SET SCHEMA projet_mgmt;'
                    ),
                    reverse_sql=(
                        'ALTER TABLE projet_mgmt.document_sharepoint '
                        'SET SCHEMA public;\n'
                        'ALTER TABLE public.document_sharepoint '
                        'RENAME TO cockpit_documentsharepoint;'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='documentsharepoint',
                    table='"projet_mgmt"."document_sharepoint"',
                ),
            ],
        ),
    ]